const ACTION_TYPES = {
  SET_INITIAL_THEME: 'SET_INITIAL_THEME',
  ADD_COLOR: 'ADD_COLOR',
  UPDATE_COLOR: 'UPDATE_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',
  UPDATE_TYPOGRAPHY_CONFIG: 'UPDATE_TYPOGRAPHY_CONFIG',
  UPDATE_SPACING_CONFIG: 'UPDATE_SPACING_CONFIG',
};

export default ACTION_TYPES;
